ITEM.name = "Этанол"
ITEM.description = "Стеклянная ёмкость со спиртом внутри."
ITEM.model = "models/props_junk/glassjug01.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.cost = 5
ITEM.category = "Базовые компоненты"
ITEM.stackable = true
ITEM.max_stack = 8